name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install numpy pandas scikit-learn wandb jupyter opencv-python matplotlib
      - name: Run notebook
        run: jupyter execute distance-classification.ipynb
        env:
          WANDB: ${{ secrets.WANDB }}
